name: "Continuous Deployment to Cloudflare Pages"
description: "Deploy to Cloudflare Pages"

inputs:
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
  current_branch:
    description: "Compare if not production branch for preview deploys"
    required: true
  pull_request_number:
    description: "Pull request number for posting the deployment link"
    required: true
  cloudflare_account_id:
    description: "Cloudflare account id"
    required: true
  cloudflare_api_token:
    description: "Cloudflare API token"
    required: true
  commit_sha:
    description: "Commit SHA for posting the deployment link"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check for pull_request_number or commit_sha
      shell: bash
      run: |
        if [ -z "${{ inputs.pull_request_number }}" ] && [ -z "${{ inputs.commit_sha }}" ]; then
          # this is for merged pull requests, which do not contain a commit sha
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        else
          # this is for normal commits on pull requests
          echo "COMMIT_SHA=${{ inputs.commit_sha }}" >> $GITHUB_ENV
        fi

    # - name: Debug
    #   shell: bash
    #   run: | 
    #     echo ${{ inputs.cloudflare_account_id }}
    #     echo ${{ inputs.cloudflare_api_token }}

    - name: Deploy to Cloudflare
      run: bash ./.github/cloudflare-deploy.sh "${{ inputs.repository }}" "${{ inputs.production_branch }}" "${{ inputs.output_directory }}" "${{ inputs.current_branch }}"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: "JWo5dPsoyohH5PRu89-RktjCvRN0-ODC6CC9ZBqF"

    - name: Post Deployment on Pull Request or Commit
      shell: bash
      run: |
        yarn
        yarn tsx src/index.ts \
        --deployment_output "${{ env.DEPLOYMENT_OUTPUT }}" \
        --repository "${{ inputs.repository }}" \
        --pull_request_number "${{ inputs.pull_request_number }}" \
        --commit_sha "${{ env.COMMIT_SHA }}"
