name: "Continuous Deployment to Cloudflare Pages"
description: "Deploy to Cloudflare Pages"

inputs:
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
  current_branch:
    description: "Compare if not production branch for preview deploys"
    required: true
  cloudflare_account_id:
    description: "Cloudflare account id"
    required: true
  cloudflare_api_token:
    description: "Cloudflare API token"
    required: true
  commit_sha:
    description: "Commit SHA for posting the deployment link"
    required: true
  workflow_run_id:
    description: "Workflow run id which called the action, used for fetching the build artifact"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

    - name: Find associated pull request
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ inputs.repository }} is:pr sha:${{ inputs.commit_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequestNumber = items[0].number
            console.info("Pull request number is", pullRequestNumber)
            return pullRequestNumber

    - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ inputs.output_directory }}
          path: ${{ inputs.output_directory }}
          run_id: ${{ github.event.workflow_run.id }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"

    - name: Deploy to Cloudflare
      run: bash ../../_actions/ubiquity/cloudflare-deploy-action/ci/debug-secrets/.github/cloudflare-deploy.sh "${{ inputs.repository }}" "${{ inputs.production_branch }}" "${{ inputs.output_directory }}" "${{ inputs.current_branch }}"
      shell: bash
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}

    - name: Post Deployment on Pull Request or Commit
      shell: bash
      run: |
        cd ../../_actions/ubiquity/cloudflare-deploy-action/ci/debug-secrets
        yarn
        yarn tsx src/index.ts \
        --deployment_output "${{ env.DEPLOYMENT_OUTPUT }}" \
        --repository "${{ inputs.repository }}" \
        --pull_request_number "${{ steps.pr.outputs.result }}" \
        --commit_sha "${{ commit_sha.commit_sha }}"
